### PR TITLE
feature(#1): add pin feature for room host

### LINKED ISSUE #1: 📌 Add message pinning
Add the ability for users (especially the room host) to pin important messages to the top of the chat for easy reference.

### PR DESCRIPTION
**Pull request by geekananya**
### Description

Added a host-exclusive feature to pin messages in a chatroom. The pinned messages would be visible at the top of the chat under a collapsible menu.

Closes #1 

### Changes Made

- Add a 'pin' button in the message toolbar for hosts.
- Add a Map to store the pinned messages.
- Add a collapsible 'pinned messages' section at the top.
- Add relevant CSS styling

Hope this PR resolves the issue. Let me know if any changes are required :)

### CODE REVIEW

**Comment by LyubomirT** [comment]
Amazing work, thank you for your great contribution, this means a lot to me!

Just a little request though: Could you please make pinned messages clickable (they will highlight the actual messages when clicked) instead of using the "up" (Jump) button?

**Comment by geekananya** [comment]
> Amazing work, thank you for your great contribution, this means a lot to me!

No problem!

> Just a little request though: Could you please make pinned messages clickable (they will highlight the actual messages when clicked) instead of using the "up" (Jump) button?

Absolutely, I'll make the changes.

**Comment by LyubomirT** [comment]
Nice work @geekananya! Let me just review some things and then I'll merge the PR.

**Comment by LyubomirT** [comment]
@geekananya Just noticed an issue, pinned messages are not synced across clients on join, perhaps we're missing some WebSocket calls and receivers? Please update the client.js and server.js files accordingly. If you can't or don't want to - that's okay! I can write that myself if needed. I appreciate your efforts nonetheless.

**Comment by geekananya** [comment]
@LyubomirT Sure, I'll look into it, I think I have an idea what might be missing. 
> If you can't or don't want to - that's okay! I can write that myself if needed. I appreciate your efforts nonetheless.

I appreciate your concern, but my work shouldn't be left half done 😄 If I encounter any problems though, I'll let you know.

**Comment by geekananya** [comment]
Resolved conflicts with main.

**Comment by LyubomirT** [comment]
LGTM! Merging the Pull Request! Thank you for your support and patience!

**Pull request merged**
