### PR TITLE
feat: user mention

### LINKED ISSUE #3: ⚠️ Implement User Mention Feature
Add the ability to mention other users in the chat, which could trigger notifications or highlight messages for mentioned users.

### PR DESCRIPTION
**Pull request by geekananya**
### Description
Implemented a feature to allow users to mention other users, triggered by typing '@' in the text-box. The message is highlighted with a border for the user who is mentioned.

### Changes made
- Add a user picker to choose the user to mention
- Add the mention information to the associated message information
- Add relevant styling

Closes #3

### CODE REVIEW

**Comment by LyubomirT** [comment]
Thank you for your continued support! I appreciate your hard work! However, there is a little issue that prevents me from sending messages without user mentions.
image

It seems like the issue lies in this line:

```js
        const mentionedUsers = messageInput.dataset.mentions ? JSON.parse(messageInput.dataset.mentions) : null;
        const filteredMentionedUsers = mentionedUsers.filter(mention=> message.includes(`@**${mention}**`))
        ws.send(JSON.stringify({
```

Maybe this happens because mentionedUsers does not exist when we don't mention anyone?

**Comment by geekananya** [comment]
@LyubomirT, thanks for identifying the issue! I'll fix it.

Also, I'm not the best at choosing the right color schemes and styles, so feel free to suggest any alternatives.

**Comment by LyubomirT** [comment]
@geekananya Sorry for the delay. Thank you for fixing the issue! I've just reviewed the pull request, it is working perfectly now! As for the color scheme, perhaps we could use a box shadow (so it looks like it's "glowing")? I think a box shadow similar to the "active" one in the blink animation could do.

**Comment by geekananya** [comment]
@LyubomirT no problem! I've made the changes, along with a small improvement of re-focusing the input box after appending the mention.

**Comment by LyubomirT** [comment]
@geekananya LGTM! Merging the pull request, thank you for your continued support! Please let me know if there is anything I can do to repay you for your help. :)

**Comment by geekananya** [comment]
@LyubomirT please don't worry about it! It was fun, learned a lot from your project :D

**Pull request merged**
